import type { Clip, GroundTruth } from "@/lib/types";

const palette: Record<
  GroundTruth,
  { headline: string; chipLabel: string; box: string; chip: string; rule: string }
> = {
  false: {
    headline: "Verified false by public record",
    chipLabel: "False",
    box: "border-red-200 bg-gradient-to-br from-red-50 via-white to-white",
    chip: "border-red-200 bg-red-50 text-red-700",
    rule: "bg-red-500/60",
  },
  true: {
    headline: "Verified true by public record",
    chipLabel: "True",
    box: "border-emerald-200 bg-gradient-to-br from-emerald-50 via-white to-white",
    chip: "border-emerald-200 bg-emerald-50 text-emerald-700",
    rule: "bg-emerald-500/60",
  },
  sincere: {
    headline: "Verified sincere whistleblower",
    chipLabel: "Sincere",
    box: "border-blue-200 bg-gradient-to-br from-blue-50 via-white to-white",
    chip: "border-blue-200 bg-blue-50 text-blue-700",
    rule: "bg-blue-500/60",
  },
};

export function GroundTruthPanel({ clip }: { clip: Clip }) {
  const v = palette[clip.ground_truth];
  return (
    <section
      className={`rounded-2xl border p-6 shadow-sm ${v.box}`}
      aria-label="Ground truth and outcome"
    >
      <header className="mb-3 flex items-center justify-between gap-3">
        <span className="text-[11px] font-bold uppercase tracking-[0.16em] text-slate-500">
          Ground Truth
        </span>
        <span
          className={`rounded-full border px-3 py-1 text-[11px] font-bold uppercase tracking-[0.14em] ${v.chip}`}
        >
          {v.chipLabel}
        </span>
      </header>
      <div className={`mb-3 h-[3px] w-12 rounded-full ${v.rule}`} aria-hidden />
      <h3 className="font-serif text-2xl font-medium text-slate-900">{v.headline}</h3>
      <p className="mt-2 text-sm leading-relaxed text-slate-700">{clip.ground_truth_source}</p>
      <p className="mt-3 text-xs italic text-slate-500">
        VERDICT does not determine truth. Ground truth is the recorded historical outcome and is used to calibrate the
        model, never a label generated by the model.
      </p>
    </section>
  );
}
