import type { Clip } from "./types";

function buildTimeline(baseHr: number, baseF0: number, baseAu15: number): Clip["signals"]["timeline"] {
  return Array.from({ length: 10 }, (_, i) => {
    const t = Number((i * 0.8).toFixed(1));
    return {
      t,
      hr: baseHr + i * 2,
      f0: baseF0 + i * 1.8,
      au15: Number((baseAu15 + i * 0.12).toFixed(2)),
      deception: Math.min(96, 32 + i * 6),
    };
  });
}

const mock: Clip[] = [
  {
    schema_version: "1.0",
    clip_id: "nixon_1973",
    subject: "Richard Nixon",
    statement: "I am not a crook.",
    year: 1973,
    context: "White House press conference, Orlando, FL",
    ground_truth: "false",
    ground_truth_source: "Resigned August 1974; Watergate confirmed",
    video_url: "https://www.youtube.com/watch?v=sh163n1lJ4M",
    video_start_seconds: 14,
    video_end_seconds: 26,
    thumbnail_url: "https://img.youtube.com/vi/sh163n1lJ4M/hqdefault.jpg",
    signals: {
      hr_baseline_bpm: 74,
      hr_peak_bpm: 94,
      hr_delta_bpm: 20,
      hrv_rmssd_ms: 18.4,
      au15_max_intensity: 2.8,
      au14_max_intensity: 1.2,
      au6_present: false,
      au24_max_intensity: 2.1,
      f0_baseline_hz: 112,
      f0_peak_hz: 134,
      f0_delta_hz: 22,
      jitter_percent: 3.4,
      shimmer_db: 2.1,
      speech_rate_wpm: 124,
      hedging_count: 3,
      pronoun_drop_rate: 0.31,
      transcript: "I am not a crook. I've earned everything I've got.",
      timeline: buildTimeline(76, 115, 0.4),
    },
    scores: { deception: 84, sincerity: 31, stress: 77, confidence: 28 },
    llm_report: {
      behavioral_summary:
        "Rapid cardiovascular rise and tightening mouth activity coincide with denial emphasis.",
      comparative_profile:
        "Pattern is directionally similar to historical high-stakes defensive statements.",
      qualifications:
        "Prototype signal model; not a standalone truth determination.",
    },
    similar_clips: ["clinton_1998", "armstrong_2005"],
    signal_quality: { rppg: "real", facial_au: "real", voice: "real", transcript: "real" },
  },
  {
    schema_version: "1.0",
    clip_id: "clinton_1998",
    subject: "Bill Clinton",
    statement: "I did not have sexual relations with that woman.",
    year: 1998,
    context: "White House statement to press",
    ground_truth: "false",
    ground_truth_source: "Subsequent admission and formal inquiry record",
    video_url: "https://www.youtube.com/watch?v=KI6nNa5hA8Q",
    video_start_seconds: 8,
    video_end_seconds: 20,
    thumbnail_url: "https://img.youtube.com/vi/KI6nNa5hA8Q/hqdefault.jpg",
    signals: {
      hr_baseline_bpm: 72,
      hr_peak_bpm: 92,
      hr_delta_bpm: 20,
      hrv_rmssd_ms: 17.1,
      au15_max_intensity: 2.5,
      au14_max_intensity: 1.5,
      au6_present: false,
      au24_max_intensity: 2.4,
      f0_baseline_hz: 118,
      f0_peak_hz: 142,
      f0_delta_hz: 24,
      jitter_percent: 3.8,
      shimmer_db: 2.3,
      speech_rate_wpm: 132,
      hedging_count: 2,
      pronoun_drop_rate: 0.27,
      transcript: "I did not have sexual relations with that woman.",
      timeline: buildTimeline(74, 118, 0.5),
    },
    scores: { deception: 81, sincerity: 29, stress: 74, confidence: 35 },
    llm_report: {
      behavioral_summary: "Compressed phrasing with elevated voice contour and moderate stress profile.",
      comparative_profile:
        "Near the cluster of categorical denials later contradicted by public record.",
      qualifications: "Signal overlap exists across high-pressure truthful contexts.",
    },
    similar_clips: ["nixon_1973", "sbf_2022"],
    signal_quality: { rppg: "real", facial_au: "real", voice: "real", transcript: "real" },
  },
  {
    schema_version: "1.0",
    clip_id: "armstrong_2005",
    subject: "Lance Armstrong",
    statement: "I have never doped.",
    year: 2005,
    context: "Television interview response",
    ground_truth: "false",
    ground_truth_source: "USADA report and subsequent admission",
    video_url: "https://www.youtube.com/watch?v=YbM7nB2vs7w",
    video_start_seconds: 5,
    video_end_seconds: 18,
    thumbnail_url: "https://img.youtube.com/vi/YbM7nB2vs7w/hqdefault.jpg",
    signals: {
      hr_baseline_bpm: 70,
      hr_peak_bpm: 88,
      hr_delta_bpm: 18,
      hrv_rmssd_ms: 19.7,
      au15_max_intensity: 2.2,
      au14_max_intensity: 1.9,
      au6_present: false,
      au24_max_intensity: 2.0,
      f0_baseline_hz: 125,
      f0_peak_hz: 146,
      f0_delta_hz: 21,
      jitter_percent: 2.9,
      shimmer_db: 1.9,
      speech_rate_wpm: 138,
      hedging_count: 1,
      pronoun_drop_rate: 0.24,
      transcript: "I have never doped. Never taken performance-enhancing drugs.",
      timeline: buildTimeline(72, 124, 0.45),
    },
    scores: { deception: 78, sincerity: 34, stress: 69, confidence: 41 },
    llm_report: {
      behavioral_summary: "Direct lexical style with mild AU suppression and sustained pitch pressure.",
      comparative_profile: "Sits between overtly defensive and rehearsed-neutral public denials.",
      qualifications: "Athletic media training can confound confidence estimation.",
    },
    similar_clips: ["clinton_1998", "holmes_2018"],
    signal_quality: { rppg: "fallback", facial_au: "real", voice: "real", transcript: "real" },
  },
  {
    schema_version: "1.0",
    clip_id: "holmes_2018",
    subject: "Elizabeth Holmes",
    statement: "Our technology works across every test category.",
    year: 2018,
    context: "Public interview regarding Theranos efficacy",
    ground_truth: "false",
    ground_truth_source: "Federal trial exhibits and verdict record",
    video_url: "https://www.youtube.com/watch?v=7z4x9R8k9dA",
    video_start_seconds: 11,
    video_end_seconds: 24,
    thumbnail_url: "https://img.youtube.com/vi/7z4x9R8k9dA/hqdefault.jpg",
    signals: {
      hr_baseline_bpm: 76,
      hr_peak_bpm: 96,
      hr_delta_bpm: 20,
      hrv_rmssd_ms: 16.2,
      au15_max_intensity: 3.1,
      au14_max_intensity: 0.9,
      au6_present: false,
      au24_max_intensity: 2.7,
      f0_baseline_hz: 103,
      f0_peak_hz: 129,
      f0_delta_hz: 26,
      jitter_percent: 4.2,
      shimmer_db: 2.4,
      speech_rate_wpm: 118,
      hedging_count: 4,
      pronoun_drop_rate: 0.38,
      transcript: "The technology has always worked. We stand by the science.",
      timeline: buildTimeline(78, 104, 0.6),
    },
    scores: { deception: 86, sincerity: 26, stress: 81, confidence: 33 },
    llm_report: {
      behavioral_summary: "High stress and narrow affect range during categorical efficacy claims.",
      comparative_profile: "Falls in the upper deception/stress quadrant of the prototype map.",
      qualifications: "Audio conditions may inflate shimmer and jitter estimates.",
    },
    similar_clips: ["sbf_2022", "nixon_1973"],
    signal_quality: { rppg: "real", facial_au: "real", voice: "fallback", transcript: "real" },
  },
  {
    schema_version: "1.0",
    clip_id: "sbf_2022",
    subject: "Sam Bankman-Fried",
    statement: "I never tried to commit fraud.",
    year: 2022,
    context: "Post-collapse interview segment",
    ground_truth: "false",
    ground_truth_source: "Federal conviction and court findings",
    video_url: "https://www.youtube.com/watch?v=0YV8g4f8j5k",
    video_start_seconds: 17,
    video_end_seconds: 29,
    thumbnail_url: "https://img.youtube.com/vi/0YV8g4f8j5k/hqdefault.jpg",
    signals: {
      hr_baseline_bpm: 79,
      hr_peak_bpm: 101,
      hr_delta_bpm: 22,
      hrv_rmssd_ms: 14.9,
      au15_max_intensity: 2.9,
      au14_max_intensity: 1.3,
      au6_present: false,
      au24_max_intensity: 2.5,
      f0_baseline_hz: 128,
      f0_peak_hz: 155,
      f0_delta_hz: 27,
      jitter_percent: 4.6,
      shimmer_db: 2.8,
      speech_rate_wpm: 152,
      hedging_count: 7,
      pronoun_drop_rate: 0.42,
      transcript: "I don't think I ever knowingly did anything fraudulent.",
      timeline: buildTimeline(80, 129, 0.55),
    },
    scores: { deception: 89, sincerity: 22, stress: 85, confidence: 24 },
    llm_report: {
      behavioral_summary: "Strong arousal and heavy hedging markers under direct responsibility prompts.",
      comparative_profile: "Most similar to high-variance crisis-denial profiles in this archive.",
      qualifications: "Interpretation should be paired with legal context and full interview length.",
    },
    similar_clips: ["holmes_2018", "clinton_1998"],
    signal_quality: { rppg: "real", facial_au: "fallback", voice: "real", transcript: "real" },
  },
  {
    schema_version: "1.0",
    clip_id: "haugen_2021",
    subject: "Frances Haugen",
    statement: "The company repeatedly chose profit over public safety.",
    year: 2021,
    context: "Congressional testimony",
    ground_truth: "sincere",
    ground_truth_source: "Corroborated internal documents and hearing record",
    video_url: "https://www.youtube.com/watch?v=_Lx5VmAdZSI",
    video_start_seconds: 21,
    video_end_seconds: 34,
    thumbnail_url: "https://img.youtube.com/vi/_Lx5VmAdZSI/hqdefault.jpg",
    signals: {
      hr_baseline_bpm: 73,
      hr_peak_bpm: 84,
      hr_delta_bpm: 11,
      hrv_rmssd_ms: 24.2,
      au15_max_intensity: 1.1,
      au14_max_intensity: 0.8,
      au6_present: true,
      au24_max_intensity: 0.9,
      f0_baseline_hz: 186,
      f0_peak_hz: 201,
      f0_delta_hz: 15,
      jitter_percent: 2.1,
      shimmer_db: 1.3,
      speech_rate_wpm: 121,
      hedging_count: 1,
      pronoun_drop_rate: 0.11,
      transcript: "I saw that choices were made repeatedly to prioritize engagement over safety.",
      timeline: buildTimeline(73, 186, 0.18),
    },
    scores: { deception: 26, sincerity: 82, stress: 48, confidence: 73 },
    llm_report: {
      behavioral_summary:
        "Lower deception trajectory with stable pacing and comparatively open facial signature.",
      comparative_profile: "Closest to high-sincerity, moderate-stress testimony patterns.",
      qualifications: "Institutional hearing format can suppress natural conversational variance.",
    },
    similar_clips: ["armstrong_2005", "nixon_1973"],
    signal_quality: { rppg: "real", facial_au: "real", voice: "real", transcript: "real" },
  },
];

export default mock;
